version: "3.9"

services:
  api:
    container_name: api_prod_categories_container
    image: api_prod_categories_image
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB=${DB}
      - DB_PORT=${DB_PORT}

  db:
    container_name: db
    image: postgres:12-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB}

    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  db_tests:
    container_name: db_tests
    image: postgres:12-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_TEST}

    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
